
-- community 게시판
Insert into GLOW_UP.TB_COMMUNITY (COMU_NO,COMU_TITLE,COMU_CONTENT,COMU_REG_ID,COMU_MOD_ID,COMU_REG_DATE,COMU_MOD_DATE,COMU_HIT) values ('A' || LPAD(COMMUNITY_SEQ.NEXTVAL, 5, 0)),'[Special Kit] 스페셜 키트 소개해드림','누구에게나 쉬운 그림자 쉐딩<br/><br/>쉐딩은 어렵다? 이제 불타는 고구마는 없다!<br/>한 듯 안 한 듯, 자연스러운 그림자 쉐딩을 추천합니다.<br/><br/>Contour Powder<br/>붉은기 없는 자연스러운 음영<br/>그림자 쉐딩<br/><br/>내 피부에서 딱 반톤 내린 듯한 자연스러운 그림자 컬러<br/><br/>컬러 분리로 색 침범 없이.<br/>2단계 강약으로 뭉침없이 쉽고 빠르게.<br/>쉽고 + 안 망하고 + 자연스러운<br/>쉐딩 개발하기 with 뷰티 유투버<br/>어렵게 섞어 쓸 걱정 없이 제대로 된 컬러만 충분히 담아냈다!<br/><br/>Contour Powder<br/>Brush<br/>비건 인증 인조모 100%<br/>눈·코·턱 영역 맞춤 사이즈<br/><br/>브러쉬 모에 구리 (CU) 소재 적용','USER00004','USER00004','2023-03-22 16:00','2023-03-22 16:00',2);
Insert into GLOW_UP.TB_COMMUNITY (COMU_NO,COMU_TITLE,COMU_CONTENT,COMU_REG_ID,COMU_MOD_ID,COMU_REG_DATE,COMU_MOD_DATE,COMU_HIT) values ('A' || LPAD(COMMUNITY_SEQ.NEXTVAL, 5, 0)),'[Beauty Awards] 내가고른 1위','누구에게나 쉬운 그림자 쉐딩<br/><br/>쉐딩은 어렵다? 이제 불타는 고구마는 없다!<br/>한 듯 안 한 듯, 자연스러운 그림자 쉐딩을 추천합니다.<br/><br/>Contour Powder<br/>붉은기 없는 자연스러운 음영<br/>그림자 쉐딩<br/><br/>내 피부에서 딱 반톤 내린 듯한 자연스러운 그림자 컬러<br/><br/>컬러 분리로 색 침범 없이.<br/>2단계 강약으로 뭉침없이 쉽고 빠르게.<br/>쉽고 + 안 망하고 + 자연스러운<br/>쉐딩 개발하기 with 뷰티 유투버<br/>어렵게 섞어 쓸 걱정 없이 제대로 된 컬러만 충분히 담아냈다!<br/><br/>Contour Powder<br/>Brush<br/>비건 인증 인조모 100%<br/>눈·코·턱 영역 맞춤 사이즈<br/><br/>브러쉬 모에 구리 (CU) 소재 적용','USER00004','USER00004','2023-03-22 16:00','2023-03-22 16:00',2);
Insert into GLOW_UP.TB_COMMUNITY (COMU_NO,COMU_TITLE,COMU_CONTENT,COMU_REG_ID,COMU_MOD_ID,COMU_REG_DATE,COMU_MOD_DATE,COMU_HIT) values (('A' || LPAD(COMMUNITY_SEQ.NEXTVAL, 5, 0)),'[1st Ranker] 1번째 인기템 알려줌','누구에게나 쉬운 그림자 쉐딩<br/><br/>쉐딩은 어렵다? 이제 불타는 고구마는 없다!<br/>한 듯 안 한 듯, 자연스러운 그림자 쉐딩을 추천합니다.<br/><br/>Contour Powder<br/>붉은기 없는 자연스러운 음영<br/>그림자 쉐딩<br/><br/>내 피부에서 딱 반톤 내린 듯한 자연스러운 그림자 컬러<br/><br/>컬러 분리로 색 침범 없이.<br/>2단계 강약으로 뭉침없이 쉽고 빠르게.<br/>쉽고 + 안 망하고 + 자연스러운<br/>쉐딩 개발하기 with 뷰티 유투버<br/>어렵게 섞어 쓸 걱정 없이 제대로 된 컬러만 충분히 담아냈다!<br/><br/>Contour Powder<br/>Brush<br/>비건 인증 인조모 100%<br/>눈·코·턱 영역 맞춤 사이즈<br/><br/>브러쉬 모에 구리 (CU) 소재 적용','USER00004','USER00004','2023-03-22 16:00','2023-03-22 16:00',2);
Insert into GLOW_UP.TB_COMMUNITY (COMU_NO,COMU_TITLE,COMU_CONTENT,COMU_REG_ID,COMU_MOD_ID,COMU_REG_DATE,COMU_MOD_DATE,COMU_HIT) values (('A' || LPAD(COMMUNITY_SEQ.NEXTVAL, 5, 0)),'[Curl FIX] 마스카라 장인은 나','마스카라 장인<br/><br/>컬링 마스카라 5년 연속 1위*<br/>24시간 컬링 지속 실화를 직접 경험해 보세요.<br/><br/>3 Proof<br/><br/>처짐 · 워터 · 스머지<br/><br/>스머지 프루프 만족도 95.5%<br/>가루날림 만족도 95.9%<br/>더 우수한 컬링 고정력 91.9%<br/><br/>*2021.06 글로우픽 설문단 197명 응답결과<br/><br/>국민 BM 의견을 100% 반영하여<br/>더 강력해진 컬링 마스카라<br/><br/>컬링에 진심인 국민 BM 400명이 함께 업그레이드한 국민 컬링 마스카라<br/><br/>*워터프루프 & 스머지 프루프 실험 완료<br/><br/>화이버로 롱래쉬<br/><br/>깃털처럼 가벼운 삼각 화이버가 속눈썹에 부착되어 오랫동안 쭉쭉 길어보이게 연출 해 줍니다.<br/><br/>*래쉬 펌 컬 픽스 마스카라 롱래쉬에 한 함<br/><br/>','USER00006','USER00006','2023-03-22 16:02','2023-03-22 16:02',0);
Insert into GLOW_UP.TB_COMMUNITY (COMU_NO,COMU_TITLE,COMU_CONTENT,COMU_REG_ID,COMU_MOD_ID,COMU_REG_DATE,COMU_MOD_DATE,COMU_HIT) values (('A' || LPAD(COMMUNITY_SEQ.NEXTVAL, 5, 0)),'[Eyelash empoule] 속눈썹 영양제 추천!','속눈썹 영양제? 왜 써야 할까요?<br/><br/>Answer<br/>속눈썹은 눈 가장 가까이에 있어 예민하고 민감하기 때문에 마스카라를 바르거나 클렌징할때 세심하고 꼼꼼한 관리가 필요해요. 요즘은 속눈썹 연장, 펌도 많이 하시잖아요.<br/><br/>속눈썹 건강을 위해서라면 꼭 지속적인 관리가 필요해요.<br/><br/>제품의 가장 큰 포인트는?<br/><br/>Answer<br/>이 제품의 가장 큰 포인트는 확실한 효과예요.<br/><br/>기존 파워래쉬 속눈썹 영양제의 효과는 그대로 유지하면서 눈에 좀 더 편하게 쓸 수 있도록 베이스 성분을 변경하고 또 속눈썹 한 올 한 올 꼼꼼한 케어를 위해 어플리케이터도 새롭게 개발했어요.<br/><br/>파워래쉬앰플 효능 효과는?<br/>clinical trial<br/>Answer<br/>파워 래쉬 속눈썹 영양제의 효과는 인체적용 시험을 통해 입증이 되었는데요.<br/><br/>속눈썹 개선 효능 확인을 위해 20세부터 29세까지 피험자들에게 6주간 제품을 사용하게 했고 6주간 사용 시 4주 만에 효과를 확인할 수 있었어요.<br/><br/>몇몇 분들은 속눈썹 영양제를 쓰기 꺼려하시는데 그 이유는 바로 안자극 때문이라고 생각해요. 이 제품은 안자극 대체 테스트를 완료했고 이전 대비 안자극감이 유의하게 낮아짐을 확인했습니다. 4주동안 꾸준히 사용하시면 이 제품의 효과를 충분히 경험하실 수 있을거예요.<br/><br/>[인체 적용 시험]<br/>시험기관 :<br/><br/>아이이씨코리아<br/>시험기간 :<br/><br/>2021.3.31~05.12<br/>시험대상 :<br/><br/>성인여성 29인<br/>[안자극 대체 테스트 완료]<br/>시험기간 :<br/><br/>아모레퍼시픽 R&D 안정성랩<br/>시험날짜 :<br/><br/>2021.03.11<br/>시험법 :<br/><br/>HET-CAM','USER00004','USER00004','2023-03-22 16:04','2023-03-22 16:04',0);
Insert into GLOW_UP.TB_COMMUNITY (COMU_NO,COMU_TITLE,COMU_CONTENT,COMU_REG_ID,COMU_MOD_ID,COMU_REG_DATE,COMU_MOD_DATE,COMU_HIT) values (('A' || LPAD(COMMUNITY_SEQ.NEXTVAL, 5, 0)),'[Soon Jung] 순정 크림 좋아요!','Since 1988<br/>순-하게 진정, 수<br/>1988년 글로우업 ''순정''에서부터<br/>30년간 이어진 민감 피부 연구의 노하우를 담아 낸 글로우업 순정은<br/>더욱 강해지는 피부 자극 고민에 대한 솔루션을 제안 해 주는<br/>민감 피부를 위한 저자극 진정 스킨케어 라인 입니다.<br/><br/>PANTHENSOSIDE™<br/>판텐소사이드™ 함유로<br/>피부 장벽 강화, 피부 진정 케어<br/>피부 진정에 효과적인 판테놀과 마데카소사이드가 함유되어<br/>외부 환경으로 인해 자극 받은 피부를 진정시켜 줍니다.<br/>* 원료적 특성에 한함<br/><br/>DUST CUT™<br/>외부 환경으로 인한 피부 고민 케어<br/>각종 외부 자극으로 민감해진 피부, 빠른 진정이 필요하다면?<br/>하루종일 자극받은 피부 진정, 순정<br/><br/>10-FREE<br/>10가지 주의 성분 무첨가<br/>토너 : 동물성원료, 광물성오일, 색소, 향료, 폴리아크릴아마이드, 실리콘, 이미다졸리디닐우레아, 트리에탄올아민, PEG계면활성제, 파라벤 Free<br/><br/>수분베리어크림 : 동물성원료, 광물성오일, 합성색소, 향료, 폴리아크릴아마이드, 이미다졸리디닐우레아, 트리에탄올아민, 실리콘오일, PEG계면활성제, 파라벤','USER00005','USER00005','2023-03-22 16:06','2023-03-22 16:06',0);
Insert into GLOW_UP.TB_COMMUNITY (COMU_NO,COMU_TITLE,COMU_CONTENT,COMU_REG_ID,COMU_MOD_ID,COMU_REG_DATE,COMU_MOD_DATE,COMU_HIT) values (('A' || LPAD(COMMUNITY_SEQ.NEXTVAL, 5, 0)),'[Moistfull collagen] 아침부터 쭉 촉촉했어요!','Hello<br/>수분 탄력 케어 수분가득 콜라겐<br/>아침부터 저녁까지 탱글촉촉<br/><br/>피쉬 콜라겐을 가수분해하여 미세 입자로 만든 슈퍼 콜라겐™ 워터와<br/>슈퍼 플랜트 화이트 루핀이 함유되어 피부 속 깊숙이 콜라겐 수분을 충전해 주는<br/>수분 탄력 케어 라인입니다.<br/><br/><br/>#저분자콜라겐  #저자극수분크림  #순한보습<br/><br/>HISTORY<br/>수분가득 콜라겐 4번째 업그레이드<br/>어떤 점들이 좋아졌을까요? <br/><br/>#수분가득크림 #국민수분크림<br/><br/>Point<br/>수분 탱글 제형의 첫 수분가득 크림 라인 출시<br/><br/>더욱 순하고 촉촉한<br/>저자극 수분 크림<br/><br/>피부를 편안하게, 건강한 수분 포뮬라에<br/>7가지 성분 무첨가<br/><br/>수분가득 콜라겐수분가득 콜라겐<br/>저자극 포뮬러를 검증하는<br/>인체 적용 시험을 통과했습니다.<br/><br/>피부에 알러지 자극을 주는지 여부 확인 테스트<br/>제품 사용 시 기본적인 피부 이상 반응 여부 확인 시험 완료<br/>제품 사용 시 피부 자극 이상 반응 여부 확인 시험 완료<br/><br/>수분가득 콜라겐수분가득 콜라겐<br/>즉각적 피부 보습* · 피부결 개선 효과<br/>검증을 완료하였습니다.<br/><br/>바르자마자 탱글하게 차오르는 수분감<br/>단 1회 사용만에 피부결 개선 효과<br/><br/>* 자세한 내용은 제품 상세페이지를 참고해 주세요.<br/><br/>수분가득 콜라겐<br/>대표 성분 2가지<br/>653,800ppm 이 숫자가 의미하는 건<br/>입자가 작은 슈퍼콜라겐™ 워터 함유량<br/>','USER00004','USER00004','2023-03-22 16:07','2023-03-22 16:07',0);
Insert into GLOW_UP.TB_COMMUNITY (COMU_NO,COMU_TITLE,COMU_CONTENT,COMU_REG_ID,COMU_MOD_ID,COMU_REG_DATE,COMU_MOD_DATE,COMU_HIT) values (('A' || LPAD(COMMUNITY_SEQ.NEXTVAL, 5, 0)),'[Special Store] 뷰티스토어 투어 - 강남점','강남 쇼룸<br/>가장 프로페셔널한 메이크업 서비스를 만나는 곳<br/><br/>위치<br/>도로명: 서울 서초구 강남대로 415 (서초동)<br/>지번: 서울 서초구 서초동 1306-8<br/>번호<br/>02-4567-8910<br/><br/>월-일 오전 11시 ~ 오후 9시<br/>아이브로우바 02-1234-5678<br/><br/>뷰티크루 터치업 서비스<br/>뷰티크루 터치업 서비스<br/><br/>아이브로우 바<br/><br/>친근하면서 자유분방한 글로우업을<br/>온전히 체험할 수 있는 공간.<br/><br/>Skin Tone Consulting<br/>‘프로 테일러 파운데이션 비글로우’를 직접 경험해보고 자신의 피부 톤에 맞는 파운데이션을 찾을 수 있는 스킨톤 컨설팅 서비스<br/><br/>Powder & Play<br/>섀도우 팔레트에 대한 고객의 의견을 반영하여 고안된 서비스로 고객이 총 30가지의 파우더 중 3가지를 직접 조합, 프레스하여 원하는 디자인의 파우더를 제작할 수 있는 서비스','USER00005','USER00005','2023-03-22 16:42','2023-03-22 16:43',2);
Insert into GLOW_UP.TB_COMMUNITY (COMU_NO,COMU_TITLE,COMU_CONTENT,COMU_REG_ID,COMU_MOD_ID,COMU_REG_DATE,COMU_MOD_DATE,COMU_HIT) values (('A' || LPAD(COMMUNITY_SEQ.NEXTVAL, 5, 0)),'[Cosmetic Ingredient] 화장품 원료 알아봄','강남 쇼룸<br/>가장 프로페셔널한 메이크업 서비스를 만나는 곳<br/><br/>위치<br/>도로명: 서울 서초구 강남대로 415 (서초동)<br/>지번: 서울 서초구 서초동 1306-8<br/>번호<br/>02-4567-8910<br/><br/>월-일 오전 11시 ~ 오후 9시<br/>아이브로우바 02-1234-5678<br/><br/>뷰티크루 터치업 서비스<br/>뷰티크루 터치업 서비스<br/><br/>아이브로우 바<br/><br/>친근하면서 자유분방한 글로우업을<br/>온전히 체험할 수 있는 공간.<br/><br/>Skin Tone Consulting<br/>‘프로 테일러 파운데이션 비글로우’를 직접 경험해보고 자신의 피부 톤에 맞는 파운데이션을 찾을 수 있는 스킨톤 컨설팅 서비스<br/><br/>Powder & Play<br/>섀도우 팔레트에 대한 고객의 의견을 반영하여 고안된 서비스로 고객이 총 30가지의 파우더 중 3가지를 직접 조합, 프레스하여 원하는 디자인의 파우더를 제작할 수 있는 서비스','USER00004','USER00004','2023-03-22 16:42','2023-03-22 16:43',2);
Insert into GLOW_UP.TB_COMMUNITY (COMU_NO,COMU_TITLE,COMU_CONTENT,COMU_REG_ID,COMU_MOD_ID,COMU_REG_DATE,COMU_MOD_DATE,COMU_HIT) values (('A' || LPAD(COMMUNITY_SEQ.NEXTVAL, 5, 0)),'[Countour] 쉬운 그림자 쉐딩해봄','강남 쇼룸<br/>가장 프로페셔널한 메이크업 서비스를 만나는 곳<br/><br/>위치<br/>도로명: 서울 서초구 강남대로 415 (서초동)<br/>지번: 서울 서초구 서초동 1306-8<br/>번호<br/>02-4567-8910<br/><br/>월-일 오전 11시 ~ 오후 9시<br/>아이브로우바 02-1234-5678<br/><br/>뷰티크루 터치업 서비스<br/>뷰티크루 터치업 서비스<br/><br/>아이브로우 바<br/><br/>친근하면서 자유분방한 글로우업을<br/>온전히 체험할 수 있는 공간.<br/><br/>Skin Tone Consulting<br/>‘프로 테일러 파운데이션 비글로우’를 직접 경험해보고 자신의 피부 톤에 맞는 파운데이션을 찾을 수 있는 스킨톤 컨설팅 서비스<br/><br/>Powder & Play<br/>섀도우 팔레트에 대한 고객의 의견을 반영하여 고안된 서비스로 고객이 총 30가지의 파우더 중 3가지를 직접 조합, 프레스하여 원하는 디자인의 파우더를 제작할 수 있는 서비스','USER00006','USER00006','2023-03-22 16:42','2023-03-22 16:43',2);

-- event 게시판
Insert into GLOW_UP.TB_EVENT (EV_NO,EV_TITLE,EV_CONTENT,EV_REG_ID,EV_MOD_ID,EV_REG_DATE,EV_MOD_DATE,EV_HIT) values (('B' || LPAD(EVENT_SEQ.NEXTVAL, 5, 0)),'[HOT] Glow up 쇼핑몰 론칭 기념','NEW 비내추럴 쿠션 론칭 기념 BIG SALE<br/>관리받은 듯 강력한 스킨케어링 효과의 <br/><br/>#반질광쿠션<br/><br/>2023.03.22 - 2023.03.22<br/><br/>','USER00002',null,'2023-03-22 16:44','2023-03-22 16:44',0);
Insert into GLOW_UP.TB_EVENT (EV_NO,EV_TITLE,EV_CONTENT,EV_REG_ID,EV_MOD_ID,EV_REG_DATE,EV_MOD_DATE,EV_HIT) values (('B' || LPAD(EVENT_SEQ.NEXTVAL, 5, 0)),'[EVENT] 회원 문자 이벤트 참여','NEW 비내추럴 쿠션 론칭 기념 BIG SALE<br/>관리받은 듯 강력한 스킨케어링 효과의 <br/><br/>#반질광쿠션<br/><br/>2023.03.22 - 2023.03.22<br/><br/>','USER00002',null,'2023-03-22 16:44','2023-03-22 16:44',0);
Insert into GLOW_UP.TB_EVENT (EV_NO,EV_TITLE,EV_CONTENT,EV_REG_ID,EV_MOD_ID,EV_REG_DATE,EV_MOD_DATE,EV_HIT) values (('B' || LPAD(EVENT_SEQ.NEXTVAL, 5, 0)),'[NEW] 비내추럴 쿠션 론칭 기념','NEW 비내추럴 쿠션 론칭 기념 BIG SALE<br/>관리받은 듯 강력한 스킨케어링 효과의 <br/><br/>#반질광쿠션<br/><br/>2023.03.22 - 2023.03.22<br/><br/>','USER00002',null,'2023-03-22 16:44','2023-03-22 16:44',0);
Insert into GLOW_UP.TB_EVENT (EV_NO,EV_TITLE,EV_CONTENT,EV_REG_ID,EV_MOD_ID,EV_REG_DATE,EV_MOD_DATE,EV_HIT) values (('B' || LPAD(EVENT_SEQ.NEXTVAL, 5, 0)),'[EVENT] GLOW UP BENEFIT LOUNGE','GLOW UP BENEFIT LOUNGE<br/><br/>더 커진 글로우업 공식몰만의 특별한 혜택<br/><br/>2023.03.22 - 2023.03.31','USER00002',null,'2023-03-22 16:46','2023-03-22 16:46',0);
Insert into GLOW_UP.TB_EVENT (EV_NO,EV_TITLE,EV_CONTENT,EV_REG_ID,EV_MOD_ID,EV_REG_DATE,EV_MOD_DATE,EV_HIT) values (('B' || LPAD(EVENT_SEQ.NEXTVAL, 5, 0)),'[OFFER] HOT DEAL','<br/>D-9<br/><br/>HOT DEAL<br/><br/>2022.12.15 - 2023.03.31','USER00002',null,'2023-03-22 16:47','2023-03-22 16:47',0);
Insert into GLOW_UP.TB_EVENT (EV_NO,EV_TITLE,EV_CONTENT,EV_REG_ID,EV_MOD_ID,EV_REG_DATE,EV_MOD_DATE,EV_HIT) values (('B' || LPAD(EVENT_SEQ.NEXTVAL, 5, 0)),'[MEMBERSHIP] 맞춤형 혜택','맞춤형 혜택<br/>필요 없는 스팸메시지는 그만!<br/>고객님께 꼭 맞는 상품과 혜택을 알려드립니다.<br/><br/><br/>프라이빗 메이크업 레슨<br/>전문 메이크업 아티스트가 1:1로<br/>고객님께 어울리는 메이크업을 알려드립니다.<br/><br/>글로우업 회원가입하고 모든 혜택을 누려보세요!<br/><br/>유의사항<br/><br/>2018년 1월 1일부터 글로우업 멤버십 등급이 일원화 되었습니다. (기존 회원등급제(Members, VVIP)에 따른 혜택 종료)<br/>SNS회원은 글로우업 쇼핑몰 회원 계정 연동 이후부터 멤버십 혜택 적용 대상이 됩니다.','USER00002',null,'2023-03-22 16:48','2023-03-22 16:48',0);
Insert into GLOW_UP.TB_EVENT (EV_NO,EV_TITLE,EV_CONTENT,EV_REG_ID,EV_MOD_ID,EV_REG_DATE,EV_MOD_DATE,EV_HIT) values (('B' || LPAD(EVENT_SEQ.NEXTVAL, 5, 0)),'[EVENT] 뷰티포인트 추가적립 안내','글로우업의 통합 멤버십 서비스를 누릴 수 있는<br/>글로우업 뷰티포인트 통합회원을 신청하세요.<br/><br/>글로우업 결제금액의 1%가<br/>뷰티포인트로 적립됩니다.<br/><br/><br/>뷰티포인트 통합회원이 아닌 경우<br/>글로우업 제품 구매시<br/>포인트가 적립되지 않습니다.<br/><br/><br/>1. 제품 구매 포인트 적립<br/>모든 매장과 제품 구매 시, 결제금액의 1%를 뷰티포인트로 적립해 드립니다.<br/><br/>유의사항<br/><br/>제품 구매 시, 연간 적립 가능한 최대 뷰티포인트는 50만 포인트로 제한되며 초과분에 대해서는 포인트 적립이 되지 않습니다.<br/>제품 환불 시, 적립된 뷰티포인트도 자동으로 취소됩니다.<br/>할인쿠폰/교환권/일부 상품권으로 결제 시 뷰티포인트가 적립되지 않습니다.<br/>뷰티포인트 카드 미소지 등의 이유로 현장에서 적립을 받지 못하셨을 경우, 구매일로부터 60일 이내에 제품 구매 매장에<br/>구매 영수증이나 카드대금 청구서를 제시하면 뷰티포인트 적립이 가능합니다.<br/>내부 심사기준에 따라 특정 브랜드 구매 편중 및 적립 과다로 비정상적으로 판단될 경우 뷰티포인트가 적립되지 않습니다.<br/>뷰티포인트 적립율은 회사 정책에 따라 사전 고지 후 변동될 수 있습니다.<br/><br/>2. 공병 포인트 적립<br/>다 쓰신 플라스틱, 유리병으로 된 스킨케어 본품의 공병을 뷰티포인트로 적립해 드립니다.<br/><br/>공병 한 개당 500P (월 최대 5,000P) 적립 가능하며, 오프라인 매장(면세점, 시코르, 아리따움 등 입점매장 제외)에서 수거합니다.<br/>유효기간 : 적립일로부터 1년','USER00002',null,'2023-03-22 16:51','2023-03-22 16:51',0);
Insert into GLOW_UP.TB_EVENT (EV_NO,EV_TITLE,EV_CONTENT,EV_REG_ID,EV_MOD_ID,EV_REG_DATE,EV_MOD_DATE,EV_HIT) values (('B' || LPAD(EVENT_SEQ.NEXTVAL, 5, 0)),'[NEW] 리얼 아이 팔레트 올 뉴','NEW 리얼 아이 팔레트 올 뉴<br/><br/>34,000 >> 25,500(25% 할인)<br/><br/>소프트 톤온톤 조합의 맑은 레이어링 팔레트<br/><br/><br/><br/>제품명   리얼 아이 팔레트 올 뉴<br/>용량   1호 에브리베이지 / 7.5g<br/>2호 소프티로지 / 7.5g<br/>제품 주요 사양(피부타입, 색상(호, 번) 등)   모든 피부용<br/>사용기한   상품 발송일 기준으로 사용기한이 12개월 이상 남은 상품만을 판매<br/>사용방법   손끝이나 브러쉬를 이용하여 내용물을 적당량 취해 눈가에 부드럽게 블렌딩해줍니다.<br/>제조사/ 제조국/제조판매업자   코스맥스 / 한국 / (주)글로우업<br/>주요성분   전성분 보기<br/>기능성 화장품의 경우 화장품법에 따른<br/>식품의약품 안전처 심사 필 유무   해당없음<br/>사용할 때 주의사항   주의사항 보기<br/>소비자상담관련 전화번호   080-123-8888(수신자 요금부담)<br/>운영시간 09:00~18:00 (점심시간 11:30~12:30, 주말, 공휴일 제외)<br/>품질보증기준   본 제품에 이상이 있을 경우, 공정거래위원회 고시에 의거 보상해드립니다.<br/>제품별 제조일자는 상이할 수 있으며, 제조일자 확인을 원할 경우 고객상담실로 문의 부탁드립니다.','USER00002',null,'2023-03-22 16:54','2023-03-22 16:54',3);
Insert into GLOW_UP.TB_EVENT (EV_NO,EV_TITLE,EV_CONTENT,EV_REG_ID,EV_MOD_ID,EV_REG_DATE,EV_MOD_DATE,EV_HIT) values (('B' || LPAD(EVENT_SEQ.NEXTVAL, 5, 0)),'[NEW] The Sleek Cream Matte','THE SLEEK LIPSTICK CREAM MATTE<br/>￦ 26,000(25%)￦ 19,500<br/><br/>더슬릭 립스틱 크림매트<br/><br/><br/>직영몰 멤버십 혜택 안내<br/>The Sleek Cream Matte 지루하지 않은 컬러, 가벼운 메이크업 제스처 립스틱의 프레임을 벗어나다. <br/>더슬릭 립스틱<br/>더슬릭 립스틱 크림매트 The Sleek Cream Matte <br/><br/>#크림누드톤 #립앤치크멀티유즈<br/><br/>놀랍도록 매끈한 크림매트 텍스처가 부드럽게 퍼지며 섬세한 블러 립을 연출해주는 슬림 립스틱Don''t stick, Do The Sleek 자유롭고 쿨한 제스처로 표현하는 나만의 애티튜드<br/><br/> Vacance 바캉스 : 세련된 크림 라일락 컬러Valentine 발렌타인 : 크리미 핑크 컬러Eve 이브 : 뮤티드 크림슨 컬러Posy 포지 : 맑은 살구 누드 컬러Color Shade사계절 언제나 부드럽게 어우러지는 고급스럽고 화사한 크림누드 블렌디드 컬러 스펙트럼Valentine 발렌타인 : 딸기우윳빛 컬러를 트렌디하게 재해석한 크리미 핑크 컬러Vacance 바캉스 : 쿨톤 동양인에게 가장 세련되게 어울리는 크림 라일락 컬러Posy 포지 : 탁하지 않고 화사하면서도 고급스러운 맑은 살구 누드 컬러Eve 이브 : 바닐라크림을 섞어 뻔하지 않고 오묘한 뮤티드 크림슨 컬러 (사나 Pick!)<br/>Texture놀랍도록 매끈하고 부드러운 소프트 블러 이펙트로 부드러운 발색과 섬세한 블러 립 연출<br/><br/>뭉침 없이 부드럽게 퍼지는 섬세한 블러 효과<br/>놀랍도록 매끈한 크림매트 텍스처<br/>숨어있는 입술 경계까지 손쉬운 터치로 볼륨 립 연출<br/>자사 샘플 vs 더슬릭 립스틱 크림매트 텍스처 비교 (*본 테스트는 에스쁘아 자체 테스트 결과로 사용 결과는 개인 차가 있을 수 있습니다.)진화된 립-스킨케어링 크림매트 텍스처 : 유효한 보습효과를 주는 특허성분 발효 센텔라 오일을 10,000ppm 적용해 주름, 각질, 건조함 걱정 없이 입술 장벽을 강화하고 보습 케어 효과를 선사합니다.<br/>주름과 각질이 부각된 자사 샘플 VS 보습성분을 10,000ppm 함유한 더슬릭 립스틱 크림매트 (*원료적 특성에 한함)<br/>How to두 뺨과 눈매에 자유롭게 터치해 손쉽게 립&치크 멀티유즈 톤온톤 메이크업을 연출해 보세요!<br/>아티스트 Says하나의 톤으로 안정적인 조화를 이루며 말갛게 물들여 공들이지 않아도 손쉽게 세련된 톤온톤 메이크업을 연출해 줍니다.<br/>by. 프로 아티스트 지니<br/>아티스트 Tip 웜톤 레이어링 활용법 : Base 포지 + Point 이브<br/>아티스트 Tip 쿨톤 레이어링 활용법 : Base 발렌타인 + Point 바캉스<br/>why slim?펜 타입 8mm 슬림 쉐입으로 손쉬운 오버립 연출 : 공들이지 않아도 숨은 1mm 경계까지 섬세하게 터치해 손쉽게 도톰하고 봉긋한 오버립을 연출해 줍니다.사선 트위스트 용기로 편안한 그립감 : Tip! 용기 하단의 ''espoir'' 로고 양각을 검지로 쥐어보세요. 미끄러짐 없이 더욱 편안한 그립감을 선사합니다.<br/>Notice 사용 시 주의사항슬림한 제형이므로 1-2mm씩만 꺼내어 사용해 주세요. 너무 길게 빼내어 힘주어 사용하면 내용물 심이 부러질 수 있습니다.<br/>The Sleek LIPSTICK<br/>BEST COLOR<br/><br/>1   <br/>발렌타인<br/><br/>2   <br/>바캉스<br/><br/>3   <br/>이브<br/><br/>？<br/>상품 정보/전성분 안내<br/>본 상품정보는 [공정거래위원회의 전자상거래 등에서의 상품정보제공 고시]에 따라 작성되었습니다.<br/>제품명   더슬릭 립스틱 크림매트<br/>용량   발렌타인 / 0.9g<br/>바캉스 / 0.9g<br/>포지 / 0.9g<br/>이브 / 0.9g<br/>제품 주요 사양(피부타입, 색상(호, 번) 등)   모든 피부용<br/>사용기한   상품 발송일 기준으로 사용기한이 12월 이상 남은 상품만을 판매<br/>사용방법   입술 안쪽부터 부드럽게 펴 바릅니다.<br/>제조사/ 제조국/제조판매업자   코스맥스 / 한국 / 글로우업<br/>주요성분   전성분 보기<br/>기능성 화장품의 경우 화장품법에 따른<br/>식품의약품 안전처 심사 필 유무   해당사항 없음<br/>사용할 때 주의사항   주의사항 보기<br/>소비자상담관련 전화번호   080-123-8888(수신자 요금부담)<br/>운영시간 09:00~18:00 (점심시간 11:30~12:30, 주말, 공휴일 제외)<br/>품질보증기준   본 제품에 이상이 있을 경우, 공정거래위원회 고시에 의거 보상해드립니다.<br/>제품별 제조일자는 상이할 수 있으며, 제조일자 확인을 원할 경우 고객상담실로 문의 부탁드립니다.','USER00002',null,'2023-03-22 16:57','2023-03-22 16:57',0);
Insert into GLOW_UP.TB_EVENT (EV_NO,EV_TITLE,EV_CONTENT,EV_REG_ID,EV_MOD_ID,EV_REG_DATE,EV_MOD_DATE,EV_HIT) values (('B' || LPAD(EVENT_SEQ.NEXTVAL, 5, 0)),'[NEW] LOOKBOOK PALETTE DOHWA-JAGAE','22 F/W LOOKBOOK PALETTE DOHWA-JAGAE<br/>￦ 35,000(50%)￦ 17,500<br/><br/><br/>22 F/W 룩북팔레트 도화자개<br/><br/>전통 자개에서 영감을 받은 도화자개 룩북 팔레트<br/><br/>10번째 룩북 팔레트 발매를 기념하여 선보이는 도화자개 컬렉션<br/>도화 빛깔로 물들어 진주 자개처럼 반짝이는 눈매와 두 뺨을 연출하는 도화자개 룩북 팔레트<br/><br/><br/>제품명   ES.22 F/W 룩북팔레트 도화자개<br/>용량   ES.22 F/W 룩북팔레트 도화자개 8G / 8g<br/>제품 주요 사양(피부타입, 색상(호, 번) 등)   모든 피부용<br/>사용기한   상품 발송일 기준으로 사용기한이 12개월 이상 남은 상품만을 판매<br/>사용방법   손끝 혹은 브러쉬를 이용하여 부드럽게 펴발라 줍니다.<br/>제조사/ 제조국/제조판매업자   코스맥스 / 대한민국 / (주)글로우업<br/>주요성분   전성분 보기<br/>기능성 화장품의 경우 화장품법에 따른<br/>식품의약품 안전처 심사 필 유무   해당없음<br/>사용할 때 주의사항   주의사항 보기<br/>소비자상담관련 전화번호   080-123-8888(수신자 요금부담)<br/>운영시간 09:00~18:00 (점심시간 11:30~12:30, 주말, 공휴일 제외)<br/>품질보증기준   본 제품에 이상이 있을 경우, 공정거래위원회 고시에 의거 보상해드립니다.','USER00002',null,'2023-03-22 16:58','2023-03-22 16:58',0);

-- 공지사항 게시판
Insert into GLOW_UP.TB_NOTICE (NTC_NO,NTC_TITLE,NTC_CONTENT,NTC_REG_ID,NTC_REG_DATE,NTC_MOD_DATE,NTC_HIT) values (('N' || LPAD(NOTICE_SEQ.NEXTVAL, 5, 0)),'[공지] Glow up 개인정보처리방침 일부가 변경됩니다.','Glow up 을 이용해 주시는 고객님께 감사드립니다.<br/><br/>2023년 2월 9일, 개인정보처리 방침의 일부 내용이 아래와 같이 변경됨을 안내드립니다.<br/><br/>■ 변경약관 시행일 : ''23.2.9<br/><br/>■ 주요 변경 사항 :<br/><br/>*  제6조(개인정보 보호업무 및 관련 고충사항처리 부서) 변경<br/>개인정보보호 책임자 변경 : (주)글로우업 구록우<br/> <br/><br/>변경되는 개인정보처리 방침은 2023년 2월 9일부터 적용될 예정입니다.<br/><br/>감사합니다.','USER00002','2023-03-22 15:44','2023-03-22 15:44',1);
Insert into GLOW_UP.TB_NOTICE (NTC_NO,NTC_TITLE,NTC_CONTENT,NTC_REG_ID,NTC_REG_DATE,NTC_MOD_DATE,NTC_HIT) values (('N' || LPAD(NOTICE_SEQ.NEXTVAL, 5, 0)),'[공지] 영상정보기기 운영관리 방침이 변경됩니다.','안녕하세요. Glow up입니다.<br/><br/>Glow up 영상정보처리기기 운영ㆍ관리 방침이 아래와 같이 변경됨을 안내드립니다.<br/><br/> <br/><br/>- 아래  -<br/><br/> <br/><br/>▶ 변경 내용<br/>직영매장 영상정보처리기기 설치대수 : 8대(기존 81대)<br/>관리책임자 변경 : (주) 글로우업 GTM팀 신도림 팀장(02-1234-5678)<br/>▶ 적용 일자<br/><br/>- 2022년 10월 28일<br/><br/> <br/><br/>감사합니다.','USER00002','2023-03-22 15:48','2023-03-22 15:48',0);
Insert into GLOW_UP.TB_NOTICE (NTC_NO,NTC_TITLE,NTC_CONTENT,NTC_REG_ID,NTC_REG_DATE,NTC_MOD_DATE,NTC_HIT) values (('N' || LPAD(NOTICE_SEQ.NEXTVAL, 5, 0)),'[공지] 소비자 가격 인상 안내','오늘도 Glow up을 찾아주신 고객님께 감사드립니다.<br/><br/>Glow up은 그동안 고객 여러분께 좋은 성분의 제품을 합리적인 가격에 제공하기 위해 지속적으로 노력해 왔으나, 계속되는 원자재 및 인건비 상승 등 외부요인으로 인해 일부 품목의 가격을 부득이하게 인상하게 되었습니다.<br/>Glow up을 아껴주시는 고객 여러분들의 너그러운 양해 부탁드리며, 변함없는 품질과 서비스로 보답하는 Glow up이 되겠습니다.<br/><br/>일부 상품 가격 인상 추가로 재 안내 드리게 된 점 양해 부탁드립니다.<br/><br/>- 가격 인상 제품 23년 2월01일 00:00 이후 적용<br/><br/>< CLEANSING >   <br/>베이킹 파우더 모공 클렌징 폼 160g :  7,000 >>  8,000<br/>베이킹 파우더 B.B 딥 클렌징 폼 160ml : 8,000 >> 9,000<br/>FACE   빅 커버 스킨 핏 컨실러 PRO 7g :  8,000 >> 11,000<br/>더블 래스팅 파운데이션 SPF35/PA++ 30g :  22,000 >> 29,000<br/>더블 래스팅 쿠션 매트 SPF50+PA++++ 15g : 22,000 >> 26,000<br/>더블 래스팅 쿠션 매트 SPF50+PA++++ (리필) : 14,000 >> 18,000<br/><br/><br/>- 감사합니다.','USER00002','2023-03-22 15:51','2023-03-22 15:51',0);
Insert into GLOW_UP.TB_NOTICE (NTC_NO,NTC_TITLE,NTC_CONTENT,NTC_REG_ID,NTC_REG_DATE,NTC_MOD_DATE,NTC_HIT) values (('N' || LPAD(NOTICE_SEQ.NEXTVAL, 5, 0)),'[공지] 과거 구매 내역 확인 안내','안녕하세요.<br/>Glow up입니다.<br/><br/>회원님의 과거 구매내역에 대해 문의사항이 있으실 경우<br/><br/>파일을 다운받아 양식에 맞게 작성 후 Glow up 대표메일(Glow up_master@Glow up.co.kr)로 요구서 첨부와 함께 문의 부탁 드립니다.<br/><br/>( + 대리인이 작성을 하여 요청주시는 경우 위임장도 함께 첨부 부탁드립니다.)<br/><br/>과거 글로우업닷컴 혹은 글로우업 오프라인 매장에서 구매한 내역에 대해서만 확인 가능합니다.<br/>오픈마켓에서 구매한 내역은 각 오픈마켓 상담실읕 통해 문의부탁드립니다.<br/><br/>글로우업 오프라인 매장 구매내역은 뷰티포인트 앱을 통해 좀 더 빠르게 확인 가능하십니다.<br/><br/>감사합니다.','USER00002','2023-03-22 15:53','2023-03-22 15:53',0);
Insert into GLOW_UP.TB_NOTICE (NTC_NO,NTC_TITLE,NTC_CONTENT,NTC_REG_ID,NTC_REG_DATE,NTC_MOD_DATE,NTC_HIT) values (('N' || LPAD(NOTICE_SEQ.NEXTVAL, 5, 0)),'[공지] 회원 로그인 기능 종료에 따른 약관 변경 안내','안녕하세요, 글로우업입니다.<br/><br/>2022년 7월 21일, 글로우업 브랜드 사이트의 회원제도 및 로그인 기능 종료에 따라 이용약관이 아래와 같이 개정될 예정임을 안내드립니다.<br/><br/>이에 따라 회원제도를 전제로 당사가 수집 및 보관 중인 회원정보/개인정보(SNS 계정 연동 정보, 구매자 리뷰 등)는 변경 약관 시행일 기준 삭제될 예정이며 로그인 기능 종료와 함께 출석체크 서비스도 함께 종료됩니다.<br/><br/>단, 전자상거래 등에서의 소비자보호에 관한 법률 등 관련 법령(전자상거래법 제6조 및 동법 시행령 제5조의2)과 당사의 개인정보처리방침 제5조 등에 따라 보존의무가 존재하는 사항에 대해서는 유지됩니다.<br/><br/>-- 아래 --<br/><br/>■ 변경약관 시행일 : ''22. 7. 21<br/>■ 주요 변경 사항 :<br/>- 제10조 (회원가입) 삭제<br/>- 제11조 (회원 탈퇴 및 자격 상실 등) 삭제<br/>- 제12조 (회원에 대한 통지) 삭제<br/>- 제13조 (회원의 ID 및 비밀번호에 대한 의무) 삭제<br/>- 제15조 (포인트 등 운영) 삭제<br/>- 제16조 (포인트 삭감 및 소멸) 삭제<br/>','USER00002','2023-03-22 15:54','2023-03-22 15:54',0);
Insert into GLOW_UP.TB_NOTICE (NTC_NO,NTC_TITLE,NTC_CONTENT,NTC_REG_ID,NTC_REG_DATE,NTC_MOD_DATE,NTC_HIT) values (('N' || LPAD(NOTICE_SEQ.NEXTVAL, 5, 0)),'[공지] 시스템 점검 안내','안녕하세요. 글로우업입니다. <br/>사이트 서버 점검으로 인해 서비스 일시 중단 예정 공지 드립니다.<br/><br/><br/>   - 기간 :  2023/01/07/(토) 오전 00:30~08:30<br/>   - 사이트 : 글로우업 PC / 모바일<br/>   - 내용 : 사이트 접속 일시 중단 가능','USER00002','2023-03-22 16:36','2023-03-22 16:36',0);
Insert into GLOW_UP.TB_NOTICE (NTC_NO,NTC_TITLE,NTC_CONTENT,NTC_REG_ID,NTC_REG_DATE,NTC_MOD_DATE,NTC_HIT) values (('N' || LPAD(NOTICE_SEQ.NEXTVAL, 5, 0)),'[공지] 생일 축하 쿠폰 사용 관련','안녕하세요. EXPECT BETTER YOU 글로우업입니다.<br/><br/> <br/><br/>기존 자동 발급되었던 20% 생일 쿠폰 사용이 잠정적 중단됨을 공지 드립니다.<br/><br/>보다 많은 고객님께 더욱 좋은 혜택으로 다시 찾아봴 예정이며 고객님들의 너른 양해 부탁 드립니다.<br/><br/> <br/><br/>감사합니다.','USER00002','2023-03-22 16:37','2023-03-22 16:37',0);
Insert into GLOW_UP.TB_NOTICE (NTC_NO,NTC_TITLE,NTC_CONTENT,NTC_REG_ID,NTC_REG_DATE,NTC_MOD_DATE,NTC_HIT) values (('N' || LPAD(NOTICE_SEQ.NEXTVAL, 5, 0)),'[공지] 9/27 고객상담실 미운영 공지','안녕하세요 EXPECT BETTER YOU 글로우업입니다.<br/><br/> <br/><br/>9월 27일 내부사정으로 고객상담실 운영이 되지 않습니다. <br/><br/>080-123-4567 대표상담번호 및 1:1 문의 응대가 어려운 점 너그러운 양해 부탁드립니다. <br/><br/>문의가 있으신 경우, 1:1 문의에 남겨주시면 <br/><br/>상담이 재개되는 9/28일 부터 순차적으로 답변해 드리도록 하겠습니다. <br/><br/> <br/><br/>* 결제 완료 후 주문 취소를 원하시는 경우 마이페이지에서 취소 가능합니다.<br/><br/>(상품준비중 단계에서는 취소가 불가하니 양해 부탁드립니다.)<br/><br/>감사합니다.','USER00002','2023-03-22 16:37','2023-03-22 16:37',1);
Insert into GLOW_UP.TB_NOTICE (NTC_NO,NTC_TITLE,NTC_CONTENT,NTC_REG_ID,NTC_REG_DATE,NTC_MOD_DATE,NTC_HIT) values (('N' || LPAD(NOTICE_SEQ.NEXTVAL, 5, 0)),'[공지] PLAY 컨텐츠 운영 종료 안내','안녕하세요 EXPECT BETTER YOU 글로우업입니다.<br/><br/>금일 기준(7월 14일) 에스쁘아 공식몰에서 운영하던 PLAY시리즈 제작 컨텐츠가 운영 종료되어 내용 안내드립니다.<br/><br/>운영 종료 서비스:  파우더&플레이/글리터&플레이<br/><br/> <br/><br/>항상 글로우업을 사랑해주시는 고객님들께 진심으로 감사의 말씀드리며<br/><br/>더욱 신선하고 새로운 서비스와 컨텐츠로 고객님들과 다시 만날 수 있도록 노력하겠습니다.<br/><br/> <br/><br/>감사합니다.','USER00002','2023-03-22 16:38','2023-03-22 16:38',0);
Insert into GLOW_UP.TB_NOTICE (NTC_NO,NTC_TITLE,NTC_CONTENT,NTC_REG_ID,NTC_REG_DATE,NTC_MOD_DATE,NTC_HIT) values (('N' || LPAD(NOTICE_SEQ.NEXTVAL, 5, 0)),'[공지] Glow up포인트 소멸 안내','안녕하세요 EXPECT BETTER YOU 글로우업입니다.<br/><br/>금일 기준(7월 14일) 에스쁘아 공식몰에서 운영하던 PLAY시리즈 제작 컨텐츠가 운영 종료되어 내용 안내드립니다.<br/><br/>운영 종료 서비스:  파우더&플레이/글리터&플레이<br/><br/> <br/><br/>항상 글로우업을 사랑해주시는 고객님들께 진심으로 감사의 말씀드리며<br/><br/>더욱 신선하고 새로운 서비스와 컨텐츠로 고객님들과 다시 만날 수 있도록 노력하겠습니다.<br/><br/> <br/><br/>감사합니다.','USER00002','2023-03-22 16:38','2023-03-22 16:38',0);

-- 1:1 문의 게시판
Insert into TB_INQUIRY (INQ_NO, INQ_TITLE, INQ_CONTENT, INQ_PHONE, INQ_EMAIL, INQ_REG_ID, INQ_REG_DATE, INQ_MOD_ID, INQ_MOD_DATE) VALUES (('A' || LPAD(INQUIRY_SEQ.NEXTVAL, 5, 0)), '화장품 용기', '환경을 생각하는 아가아빠에요 화장품을 보다가 포장은 100% 친환경인데 화장품 용기는 뚜껑이나 플라스틱소재같아보여서요 용기는 소재가 어떤건지 문의드려봅니다', '010-3333-4444', 'pjs@naver.com', 'USER00005', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'), 'USER00005' , TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
Insert into TB_INQUIRY (INQ_NO, INQ_TITLE, INQ_CONTENT, INQ_PHONE, INQ_EMAIL, INQ_REG_ID, INQ_REG_DATE, INQ_MOD_ID, INQ_MOD_DATE) VALUES (('A' || LPAD(INQUIRY_SEQ.NEXTVAL, 5, 0)), '화장품 성분 문의', '화장품에 알레르기 성분이 들어있나요? 더 자세한 성분을 알고 싶어 문의 드립니다.', '010-3333-4444', 'pjs@naver.com', 'USER00005', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'), 'USER00005' , TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
Insert into TB_INQUIRY (INQ_NO, INQ_TITLE, INQ_CONTENT, INQ_PHONE, INQ_EMAIL, INQ_REG_ID, INQ_REG_DATE, INQ_MOD_ID, INQ_MOD_DATE) VALUES (('A' || LPAD(INQUIRY_SEQ.NEXTVAL, 5, 0)), '배송관련 문의', '배송 시킨지 2주가 넘었습니다. 곤지암에서 움직일 생각을 하지 않습니다. 확인 부탁드립니다.', '010-3333-4444', 'kmj@naver.com', 'USER00006', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'), 'USER00006' , TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
Insert into TB_INQUIRY (INQ_NO, INQ_TITLE, INQ_CONTENT, INQ_PHONE, INQ_EMAIL, INQ_REG_ID, INQ_REG_DATE, INQ_MOD_ID, INQ_MOD_DATE) VALUES (('A' || LPAD(INQUIRY_SEQ.NEXTVAL, 5, 0)), '가격 인상 문의', '가격 인상되는 제품 리스트는 따로 공지되지 않는 건가요? 해당 내용이 공지되지 않아 문의드립니다.', '010-3333-4444', 'kmj@naver.com', 'USER00006', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'), 'USER00006' , TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
Insert into TB_INQUIRY (INQ_NO, INQ_TITLE, INQ_CONTENT, INQ_PHONE, INQ_EMAIL, INQ_REG_ID, INQ_REG_DATE, INQ_MOD_ID, INQ_MOD_DATE) VALUES (('A' || LPAD(INQUIRY_SEQ.NEXTVAL, 5, 0)), '신제품 문의', '새 시즌은 언제부터 시작될 예정인가요? 궁금해서 문의드립니다.', '010-3333-4444', 'shm@naver.com', 'USER00004', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'), 'USER00004', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
Insert into TB_INQUIRY (INQ_NO,INQ_TITLE,INQ_CONTENT,INQ_EMAIL,INQ_PHONE,INQ_REG_ID,INQ_MOD_ID,INQ_REG_DATE,INQ_MOD_DATE) values (('A' || LPAD(INQUIRY_SEQ.NEXTVAL, 5, 0)),'제품을 사용하는데 트러블이 생겼어요.','현재 제품을 사용하고있는데 트러블이 생겼어요. <br/>교환 및 반품이 되나요?<br/><br/>','shm@naver.com','010-3333-4444','USER00004','USER00004','2023-03-28 12:18','2023-03-28 12:18');

Insert into GLOW_UP.TB_INQUIRY (INQ_NO,INQ_TITLE,INQ_CONTENT,INQ_EMAIL,INQ_PHONE,INQ_REG_ID,INQ_MOD_ID,INQ_REG_DATE,INQ_MOD_DATE) values (('A' || LPAD(INQUIRY_SEQ.NEXTVAL, 5, 0)),'안과테스트가 되었나요?','눈에 사용하는 제품은 안과 테스트가 진행되었나요?','shm@naver.com','010-3333-4444','USER00004','USER00004','2023-03-28 13:34','2023-03-28 13:36');
Insert into GLOW_UP.TB_INQUIRY (INQ_NO,INQ_TITLE,INQ_CONTENT,INQ_EMAIL,INQ_PHONE,INQ_REG_ID,INQ_MOD_ID,INQ_REG_DATE,INQ_MOD_DATE) values (('A' || LPAD(INQUIRY_SEQ.NEXTVAL, 5, 0)),'판매하는 제품은 정품인가요?','글로우업에서 판매하는 제품은 정품인가요?','shm@naver.com','010-3333-4444','USER00004','USER00004','2023-03-28 13:36','2023-03-28 13:36');
Insert into GLOW_UP.TB_INQUIRY (INQ_NO,INQ_TITLE,INQ_CONTENT,INQ_EMAIL,INQ_PHONE,INQ_REG_ID,INQ_MOD_ID,INQ_REG_DATE,INQ_MOD_DATE) values (('A' || LPAD(INQUIRY_SEQ.NEXTVAL, 5, 0)),'품절제품은 언제 입고 되나요?','품절제품은 언제 입고 되나요?','shm@naver.com','010-3333-4444','USER00004','USER00004','2023-03-28 13:37','2023-03-28 13:37');
Insert into GLOW_UP.TB_INQUIRY (INQ_NO,INQ_TITLE,INQ_CONTENT,INQ_EMAIL,INQ_PHONE,INQ_REG_ID,INQ_MOD_ID,INQ_REG_DATE,INQ_MOD_DATE) values (('A' || LPAD(INQUIRY_SEQ.NEXTVAL, 5, 0)),'무료배송 기준은 어떻게 되나요?','제품의 무료배송 기준은 어떻게 되나요?','ksy@naver.com','010-1111-2222','USER00003','USER00003','2023-03-28 13:38','2023-03-28 13:38');
Insert into GLOW_UP.TB_INQUIRY (INQ_NO,INQ_TITLE,INQ_CONTENT,INQ_EMAIL,INQ_PHONE,INQ_REG_ID,INQ_MOD_ID,INQ_REG_DATE,INQ_MOD_DATE) values (('A' || LPAD(INQUIRY_SEQ.NEXTVAL, 5, 0)),'이벤트 신청했는데 당첨 확인은 어디서 하나요?','이벤트 신청했는데 당첨 확인은 어디서 하나요?','ksy@naver.com','010-1111-2222','USER00003','USER00003','2023-03-28 13:39','2023-03-28 13:39');
Insert into GLOW_UP.TB_INQUIRY (INQ_NO,INQ_TITLE,INQ_CONTENT,INQ_EMAIL,INQ_PHONE,INQ_REG_ID,INQ_MOD_ID,INQ_REG_DATE,INQ_MOD_DATE) values (('A' || LPAD(INQUIRY_SEQ.NEXTVAL, 5, 0)),'뷰티포인트가 무엇인가요?','문자를 받았는데 뷰티포인트가 무엇인가요?','ksy@naver.com','010-1111-2222','USER00003','USER00003','2023-03-28 13:39','2023-03-28 13:39');
Insert into GLOW_UP.TB_INQUIRY (INQ_NO,INQ_TITLE,INQ_CONTENT,INQ_EMAIL,INQ_PHONE,INQ_REG_ID,INQ_MOD_ID,INQ_REG_DATE,INQ_MOD_DATE) values (('A' || LPAD(INQUIRY_SEQ.NEXTVAL, 5, 0)),'이벤트 신청했는데 문자가 안 와요!!','이벤트 신청했는데 문자가 안 와요!!<br/>어떻게 하면 되나요?','ksy@naver.com','010-1111-2222','USER00003','USER00003','2023-03-28 13:40','2023-03-28 13:40');

-- 상품평(손흥민, 김민재) 
Insert into GLOW_UP.TB_SELL (SELL_CODE,PRODUCT_CODE,USER_CODE,SELL_PRICE,SELL_COUNT,SELL_YN,SELL_DATE) values ('S0002','F0013','USER00006',67000,1,'Y','2023-03-27 11:29');
Insert into GLOW_UP.TB_REPLY (PRODUCT_CODE,USER_CODE,USER_REPLY_NO,USER_REPLY,REPLY_DATE) values ('F0013','USER00006',1,'추천받아 구매했습니다. 각질부각없이 촉촉합니다.','2023-03-27 18:13');

Insert into GLOW_UP.TB_SELL (SELL_CODE,PRODUCT_CODE,USER_CODE,SELL_PRICE,SELL_COUNT,SELL_YN,SELL_DATE) values ('S0003','F0013','USER00004',67000,1,'Y','2023-03-29 11:29');
Insert into GLOW_UP.TB_REPLY (PRODUCT_CODE,USER_CODE,USER_REPLY_NO,USER_REPLY,REPLY_DATE) values ('F0013','USER00004',1,'동료에게 선물하려고 구매했습니다. ','2023-03-29 11:30');

commit;
